config/routes.rb
Rails.application.routes.draw do



  # get 'friendships/accept', as: 'accept_friend_request'
  devise_for :users, controllers: { registrations: 'users/registrations'  }, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  
  get 'static_pages/home', as: 'home'
  authenticate :user do
    resources :likes, only: [:create, :destroy]
    resources :friendships, only: [:create, :update, :destroy]
    resources :users
    resources :posts, except: [:show]
    resources :comments, only: [:create, :destroy]
  end
  resources :posts, only: [:show]
  root 'static_pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user

  default_scope -> { order(created_at: :desc) }
  validates :content, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:destroy]

  def create
    @comment = current_user.comments.build(comment_params)
    if @comment.save
      redirect_back fallback_location: root_url, notice: 'Comment was successfully created.'
    else
      redirect_back fallback_location: root_url, :flash => { :warning => 'Comment Faild'}
    end
  end

  def destroy
    @comment.destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    def comment_params
      params.require(:comment).permit(:content, :post_id)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<li class="list-group-item p-0 m-2">
  <%= content_tag(:nav, :class => "navbar navbar-expand-sm navbar-dark #{current_user == comment.user ? "bg-dark" : "bg-secondary"}") do %>


    <%= link_to comment.user.name , user_path(comment.user) , :class => "navbar-brand"%>

    <div class="navbar-nav">
      <% if current_user == comment.user || current_user.admin? %>
        <%#= link_to 'Edit', edit_comment_path(comment), class:"nav-link"%>
        <%= link_to 'Delete', comment, method: :delete, data: { confirm: 'Are you sure?' }, class:"nav-link" %>
      <% end %>
    </div>
    <span class= "navbar-text ml-auto"> <%= time_ago_in_words(comment.created_at)%> ago </span>
  <% end %>
  <div class="container pt-4">
    <p> <%= comment.content %></div> </p>


</li>

app/views/comments/_form.html.erb
<%= form_with(model: comment, local: true) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.text_area :content , class: "form-control", placeholder: "New Comment" %>
  </div>

    <%= form.hidden_field :post_id, value: post.id %>

  <div class="actions">
    <%= form.submit "Comment", class: "btn btn-primary btn-sm mt-1 btn-block active" %>
  </div>
<% end %>