config/routes.rb
Rails.application.routes.draw do



  # get 'friendships/accept', as: 'accept_friend_request'
  devise_for :users, controllers: { registrations: 'users/registrations'  }, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  
  get 'static_pages/home', as: 'home'
  authenticate :user do
    resources :likes, only: [:create, :destroy]
    resources :friendships, only: [:create, :update, :destroy]
    resources :users
    resources :posts, except: [:show]
    resources :comments, only: [:create, :destroy]
  end
  resources :posts, only: [:show]
  root 'static_pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  default_scope -> { order(created_at: :desc) }
  validates :content, presence: true

  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all.paginate(page: params[:page], per_page: 10)
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = current_user.posts.build
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        @post.likes.build(user_id: current_user.id).save
        format.html { redirect_to root_url, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_back(fallback_location: root_url, notice: 'Post was successfully destroyed.') }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:content)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.text_area :content , class: "form-control", placeholder: "New Post" %>
  </div>

  <div class="actions">
    <%= form.submit "Share", class: "btn btn-primary btn-sm mt-1 btn-block active" %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<li class="list-group-item p-0 m-2">
  <%= content_tag(:nav, :class => "navbar navbar-expand-sm navbar-dark #{current_user == post.user ? "bg-dark" : "bg-secondary"}") do %>


    <%= link_to post.user.name , user_path(post.user) , :class => "navbar-brand"%>
    <% if post.likes.find_by(user: current_user) %>
      <% fill_color = "pink" %>
      <% method = :delete %>
      <% path = like_path(id: post.id) %>
    <% else %>
      <% fill_color = "none" %>
      <% method = :post %>
      <% path = likes_path(id: post.id) %>
    <% end %>

    <%= link_to octicon("heart", stroke: "pink", fill: fill_color,  "stroke-width": "2" , height: 32, class: "pr-1 pl-1"),
            path, method: method, :class => "navbar-link"%>
    <% if post.likes.count != 0 %>
      <span class="navbar-text pl-1 pr-4">  <%= post.likes.count %> </span>
    <% end %>
    <div class="navbar-nav">
      <% if current_user == post.user || current_user.admin? %>
        <%= link_to 'Edit', edit_post_path(post), class:"nav-link"%>
        <%= link_to 'Delete', post, method: :delete, data: { confirm: 'Are you sure?' }, class:"nav-link" %>
      <% end %>
    </div>
    <span class= "navbar-text ml-auto"> <%= time_ago_in_words(post.created_at)%> ago </span>
  <% end %>
  <div class="container pt-4">
    <p> <%= post.content %></div> </p>
    <div class="container bg-light pt-4 pb-2">
      <%= render 'comments/form', comment: post.comments.build, post: post %>
      <ul>
        <% comments = post.comments.all.paginate(page: params["comments_#{post.id}_page"], per_page: 3)%>
        <%= render comments%>
        <%= will_paginate comments , param_name: "comments_#{post.id}_page", :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer, class: "pagination-sm"%>
      </ul>

    </div>


</li>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%#= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<%= link_to 'New Post', new_post_path, class: "btn btn-primary" %>

<%= will_paginate @posts , :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer%>
<%= render @posts %>
<%= will_paginate @posts , :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer%>

<br>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%#= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<%= render @post %>